base: /
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: us
rootPageId: 1
routeEnhancers:
  -
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
websiteTitle: 'TYPO3 Site Distribution'
