services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Site\Distribution\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Site\Distribution\EventListener\ForceUidsOnImport:
    tags: { name: event.listener }
